### ISSUE TITLE
A better way to enter APX mode on Ouya

### ISSUE THREAD

**Issue by cfint** [tofurky/tegra30_debrick#11]
On the Ouya board there are pads labelled U33. To enter APX mode:

1. Short U33
2. Press power button

In addition these pads can be mapped to a GPIO in the kernel. For these reasons it is very likely this is intentionally designed as a APX mode button in the bootloader.

The pads do kind of look like they were designed to have an SMD button of some sort soldered to it. On my device I have soldered wires and mounted and external button on the case. This method is much safer than trying to glitch an IC. From my experience  it's been 100% reliable way to enter APX mode.

![EQDKvcylkw1FIU6L (1)](https://github.com/tofurky/tegra30_debrick/assets/97752140/610e8fbf-5103-4629-b23b-97aaa4449ddb)

**Comment by tofurky** [comment]
yeah, @pgwipeout pointed this out a while ago on discord. i wasn't able to get it to work in brief testing, though.

if you open a PR (ensuring markdown etc. matches existing) we could merge it as an alternate method.

**Comment by pgwipeout** [comment]
Yeah it appears it's the clock signal for the emmc, grounding it is quite effective if you have a good ground. I have a wire soldered to this pad and use the ethernet shield as the ground.

**Comment by tofurky** [comment]
oh and btw, if that image is from ifixit (which i think it is, CC license), should probably just use a cropped/downscaled version of this https://photos.app.goo.gl/TvEWSqr6ocXFk9ot5 which i took

**Comment by tofurky** [comment]
thanks for submitting PR, it's merged.
