### ISSUE TITLE
Failed to mount /cache

### ISSUE THREAD

**Issue by fadern** [tofurky/tegra30_debrick#17]
Hi,
I have a Grouper 32gb that are looping with these two errors.

E: failed to mount /cache (invalid argument)
E: Cant mount /cache/recovery/last_locale

I have followed the guide but it still loops with the same error.
I got this error when I was flashing DivestOs from [ROM][NZH54D][2024/07/05][Asus Nexus 7 2012 WiFi/3G][F2FS/EXT4]Android 7.x AOSP.

`Kalle@SLAPTOP:~/Downloads/tegra30_debrick-master$ sudo ./fusee-launcher/fusee-launcher.py ./payload/uart_payload_n7.bin -P 7330
2024-08-28 13:15:44,668 INFO:usb.core:find(): using backend "usb.backend.libusb1"

Important note: on desktop Linux systems, we currently require an XHCI host controller.
A good way to ensure you're likely using an XHCI backend is to plug your
device into a blue 'USB 3' port.

Identified a Linux system; setting up the appropriate backend.
intermezzo_size: 0x00000078
target_payload_size: 0x000005ee
Found a Tegra with Device ID: b'11fa47d43b485d01'
Stack snapshot: b'0000000000000000100000003c9f0040'
EndpointStatus_stack_addr: 0x40009f3c
ProcessSetupPacket SP: 0x40009f30
InnerMemcpy LR stack addr: 0x40009f20
overwrite_len: 0x00004f20
overwrite_payload_off: 0x00004de0
payload_first_length: 0x000005ee
overwrite_payload_off: 0x00004de0
payload_second_length: 0x00000000
b'00a0004000300040ee05000000000000'
Setting rcm msg size to 0x00030064
RCM payload (len_insecure): b'64000300'

Setting ourselves up to smash the stack...
Payload offset of intermezzo: 0x00000074
overwrite_payload_off: 0x00004de0
overwrite_len: 0x00004f20
payload_overwrite_len: 0x00004e5c
overwrite_payload_off: 0x00004de0
smash_padding: 0x000047f2
overwrite_payload_off: 0x00004de0
Uploading payload...
txing 20480 bytes total
txing 4096 bytes (0 already sent) to buf[0] 0x40003000
txing 4096 bytes (4096 already sent) to buf[1] 0x40005000
txing 4096 bytes (8192 already sent) to buf[0] 0x40003000
txing 4096 bytes (12288 already sent) to buf[1] 0x40005000
txing 4096 bytes (16384 already sent) to buf[0] 0x40003000
Smashing the stack...
sending status request with length 0x00004f20
The USB device stopped responding-- sure smells like we've smashed its stack. :)
Launch complete!
kalle@SLAPTOP:~/Downloads/tegra30_debrick-master$ sudo ./utils/nvflash_v1.13.87205_miniloader_patched --setbct --bct ./bct/nexus_7_grouper_bct.bin --configfile ./utils/flash.cfg --bl ./bootloader/bootloader-grouper-4.23.img --goNvflash v1.13.87205 started
chip uid from BR is: 0x0000000000000000015d483bd447fa11
rcm version 0X30001
System Information:
   chip name: unknown
   chip id: 0x30 major: 1 minor: 3
   chip sku: 0x83
   chip uid: 0x0000000000000000015d483bd447fa11
   macrovision: disabled
   hdcp: enabled
   jtag: disabled
   sbk burned: true
   dk burned: true
   boot device: emmc
   operating mode: 3
   device config strap: 2
   device config fuse: 17
   sdram config strap: 1

sending file: ./bct/nexus_7_grouper_bct.bin
- 6128/6128 bytes sent
./bct/nexus_7_grouper_bct.bin sent successfully
downloading bootloader -- load address: 0x80108000 entry point: 0x80108000
sending file: ./bootloader/bootloader-grouper-4.23.img
- 2150992/2150992 bytes sent
./bootloader/bootloader-grouper-4.23.img sent successfully
waiting for bootloader to initialize
bootloader downloaded successfully
kalle@SLAPTOP:~/Downloads/tegra30_debrick-master$ sudo ./utils/nvflash_v1.13.87205_miniloader_patched --resume --download EBT bootloader/bootloader-grouper-4.23.img --configfile ./utils/flash.cfg
Nvflash v1.13.87205 started
[resume mode]
sending file: bootloader/bootloader-grouper-4.23.img
- 2150992/2150992 bytes sent
bootloader/bootloader-grouper-4.23.img sent successfully
`

**Comment by tofurky** [comment]
i don't see the error you mentioned in the output. cache is blank by default so i'd just boot into fastboot and `fastboot format cache`

**Comment by fadern** [comment]
Hi,
I'm not able to access fastboot. The tablet are looping.
Please see the attached screenshot.

**Comment by fadern** [comment]
![IMG_20240829_210158](https://github.com/user-attachments/assets/db478757-001f-4451-8a21-2d2c311ba32b)
![AndroidRedTriangle-2653609067](https://github.com/user-attachments/assets/357fbdc5-ffed-4881-bbbe-8bd7fd5fdd0a)

**Comment by tofurky** [comment]
fastboot is on there as you wouldn't get to the recovery screen without it: Press and hold Volume Down, then press and hold Power.

see if it enumerates in fastboot mode. i'd do it while it's connected to a linux system with `dmesg -Tw` running in a terminal so you can see everything it's doing via usb.

if it does, try the `fastboot format cache`.

but you say it's looping? so it goes to the exclamation mark screen then immediately reboots itself back to "E: failed to mount /cache" and then to the rescue screen again?

**Comment by fadern** [comment]
[flash.cfg.txt](https://github.com/user-attachments/files/16815013/flash.cfg.txt)
[partitions.txt](https://github.com/user-attachments/files/16813920/partitions.txt)
So I tried to boot it to fastboot mode but it always ends up in the failed to mount cache loop. The dmesg -Tw doesent show any new entries while i'm trying to access fastboot. 
the google logo flashes two time before the loop.
I'm however able to access APx mode.
```
[fre aug 30 09:58:07 2024] usb 3-1: new high-speed USB device number 5 using xhci_hcd
[fre aug 30 09:58:07 2024] usb 3-1: New USB device found, idVendor=0955, idProduct=7330, bcdDevice= 1.03
[fre aug 30 09:58:07 2024] usb 3-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[fre aug 30 09:58:07 2024] usb 3-1: Product: APX
[fre aug 30 09:58:07 2024] usb 3-1: Manufacturer: NVIDIA Corp.
```
Could it be that my partition tables got corrupt or do I need to format cache? I believe that my former rom was f2fs cache...

**Comment by fadern** [comment]
Formating cache didnt help... Still same error.

```
./utils/nvflash_v1.13.87205 --resume --format_partition 10
Nvflash v1.13.87205 started
[resume mode]
Formatting partition 10 CAC please wait.. done!
```

**Comment by fadern** [comment]
I managed to flash twrp and it was access able (once). Then i formated the cache to ext3 and then back to etx4. Then I rebooted. It didnt work. Back to APX...

```
root@SLAPTOP:/home/kalle/Downloads/tegra30_debrick-master# sudo ./utils/nvflash_v1.13.87205_miniloader_patched --resume --download SOS twrp.img --configfile ./utils/flash.cfg
Nvflash v1.13.87205 started
[resume mode]
sending file: twrp.img
\ 11098112/11098112 bytes sent
twrp.img sent successfully

```


```
[fre aug 30 13:14:28 2024] usb 3-1: Product: APX
[fre aug 30 13:14:28 2024] usb 3-1: Manufacturer: NVIDIA Corp.
[fre aug 30 13:14:58 2024] usb 3-1: USB disconnect, device number 54
[fre aug 30 13:15:08 2024] usb 3-1: new high-speed USB device number 55 using xhci_hcd
[fre aug 30 13:15:09 2024] usb 3-1: New USB device found, idVendor=18d1, idProduct=4ee7, bcdDevice=99.99
[fre aug 30 13:15:09 2024] usb 3-1: New USB device strings: Mfr=2, Product=3, SerialNumber=4
[fre aug 30 13:15:09 2024] usb 3-1: Product: Android
[fre aug 30 13:15:09 2024] usb 3-1: Manufacturer: Android
[fre aug 30 13:15:09 2024] usb 3-1: SerialNumber: 015d483bd447fa11
```



But suddenly it showed the google logo and now I see it in lsusb and adb devices.



```
root@SLAPTOP:/home/kalle# lsusb
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 001 Device 003: ID 04f2:b230 Chicony Electronics Co., Ltd Integrated HP HD Webcam
Bus 001 Device 004: ID 8086:0189 Intel Corp. Centrino Advanced-N 6230 Bluetooth adapter
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 002 Device 003: ID 138a:003c Validity Sensors, Inc. VFS471 Fingerprint Reader
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 055: ID 18d1:4ee7 Google Inc. Nexus/Pixel Device (charging + debug)
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub

root@SLAPTOP:/home/kalle# adb devices
* daemon not running; starting now at tcp:5037
* daemon started successfully
List of devices attached
015d483bd447fa11        device
```

**Comment by fadern** [comment]
ok, now I solved it.

After the "cache wipe/format/(ext4->ext3->ext4)" using twrp I followed your guide once more and then I was able to access fastboot. From there I installed DivestOS.

Thank you!
