### ISSUE TITLE
47Ohm Resistor jump on Ouya

### ISSUE THREAD

**Issue by fredohenriquez** [tofurky/tegra30_debrick#3]
Hello,

I will try your method this week but Im wondering how to properly perform the APX glitch on that pin, I understand which pin I should put the resistor but its not clear where is the gound you are referring to. Could you clarify that?

Regards

**Comment by tofurky** [comment]
![image](https://user-images.githubusercontent.com/4065513/101081541-336c1100-3578-11eb-80b9-397f88e40d3c.png)
see circled metal tab.
i will try to get an updated image on there.

**Comment by fredohenriquez** [comment]
Great, thank you

**Comment by tofurky** [comment]
i updated the image, see 8fc7ce5f09af53d3659001f3f601a1f10432679b
